name: Security Scanning Pipeline

on:
  pull_request:
    branches: [main]
  # Triggers on code push for any branches
  push:
      
  # Allow manual trigger on `Actions` tab
  workflow_dispatch:

jobs:
  security-pipeline:
    permissions:
      security-events: write
    # only required for workflows in private repositories
      actions: read
      contents: read
    uses: breaktoprotect/simple-php-security-pipeline/.github/workflows/php-security-pipeline.yaml@main
    secrets: inherit
