name: Security Scanning Pipeline

on:
  pull_request:
    branches: [main]
  
  push:
    branches:
      # Trigger on any branches except main
      - '!main'
      
  # Allow manual trigger on `Actions` tab
  workflow_dispatch:

jobs:
  security-pipeline:
    permissions:
      security-events: write
    uses: breaktoprotect/simple-php-security-pipeline/.github/workflows/php-security-pipeline.yaml@main
    secrets: inherit
